const methods = {
	add: require( './add' ),
	addClass: require( './addClass' ),
	after: require( './after' ),
	append: require( './append' ),
	attr: require( './attr' ),
	before: require( './before' ),
	css: require( './css' ),
	each: require( './each' ),
	empty: require( './empty' ),
	eq: require( './eq' ),
	extend: require( './extend' ),
	has: require( './has' ),
	hasClass: require( './hasClass' ),
	height: require( './height' ),
	hide: require( './hide' ),
	html: require( './html' ),
	off: require( './off' ),
	on: require( './on' ),
	prepend: require( './prepend' ),
	prop: require( './prop' ),
	remove: require( './remove' ),
	removeClass: require( './removeClass' ),
	show: require( './show' ),
	size: require( './size' ),
	slice: require( './slice' ),
	text: require( './text' ),
	toggleClass: require( './toggleClass' ),
	width: require( './width' ),
	wrap: require( './wrap' )
}

module.exports = methods
